CREATE TABLE "GCG_5688_APPRV_NOTES"(
 "REQ_NUM" CHAR(6),
 "LINE_NUM" CHAR(3),
 "DATE_NOTES" DATE,
 "TIME_NOTES" TIME,
 "APPROVER" CHAR(8),
 "TEXT" LONGVARCHAR CASE );

CREATE UNIQUE NOT MODIFIABLE INDEX "REQSN_APPR_NOTESK00" USING 0 ON "GCG_5688_APPRV_NOTES"("REQ_NUM", "LINE_NUM", "DATE_NOTES", "TIME_NOTES", "APPROVER");